name: Portfolio
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          version: 14.15

      - name: GitHub Action for Yarn  
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install   

      - name: Creating build 
        run: yarn build

      - name: installing surge
        run: npm install -g surge
        
      - name: Deploying using surge
        run: surge ./build http://portfoliotinyweb.surge.sh/  ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
